// Themen-Cluster des Ratgebers – einzige Quelle für CMS-Feld, Artikel-Factory und Migrationen.
//
// Jeder Cluster gehört zu genau einer Kategorie. Die Reihenfolge der Liste ist die
// Reihenfolge auf den Themenseiten. Die Werte müssen mit
// src/lib/ratgeber/clusters.ts im Frontend (MarNowi/pe) übereinstimmen – dort
// stehen Überschriften und Einleitungstexte.

export const RATGEBER_CLUSTERS = [
  { value: 'pv-planung', label: 'Planung & Anlagengröße', kategorie: 'solaranlage' },
  { value: 'pv-kosten', label: 'Kosten & Wirtschaftlichkeit', kategorie: 'solaranlage' },
  { value: 'pv-ertrag', label: 'Ertrag, Betrieb & Technik', kategorie: 'solaranlage' },
  { value: 'pv-recht', label: 'Förderung, Steuern & Anmeldung', kategorie: 'solaranlage' },
  { value: 'pv-anbieter', label: 'Anbieterwahl, Verträge & Garantie', kategorie: 'solaranlage' },
  { value: 'pv-gewerbe', label: 'Gewerbe, Landwirtschaft & Mehrfamilienhaus', kategorie: 'solaranlage' },
  { value: 'speicher-nutzen', label: 'Nutzen & Speichergröße', kategorie: 'stromspeicher' },
  { value: 'speicher-kosten', label: 'Kosten, Förderung & Nachrüstung', kategorie: 'stromspeicher' },
  { value: 'speicher-technik', label: 'Technik, Aufstellort & Notstrom', kategorie: 'stromspeicher' },
  { value: 'speicher-gewerbe', label: 'Gewerbespeicher & Multi-Use', kategorie: 'stromspeicher' },
  { value: 'wallbox-planung', label: 'Planung, Kosten & Anmeldung', kategorie: 'wallbox' },
  { value: 'wallbox-pv', label: 'Laden mit Solarstrom', kategorie: 'wallbox' },
  { value: 'wallbox-last', label: 'Hausanschluss, Lastmanagement & § 14a', kategorie: 'wallbox' },
  { value: 'wp-grundlagen', label: 'Grundlagen & Auswahl', kategorie: 'waermepumpe' },
  { value: 'wp-bestand', label: 'Planung im Bestand & Heizsystem', kategorie: 'waermepumpe' },
  { value: 'wp-aufstellung', label: 'Aufstellung, Schall & Winterbetrieb', kategorie: 'waermepumpe' },
  { value: 'wp-betrieb', label: 'Betrieb & Optimierung', kategorie: 'waermepumpe' },
  { value: 'wp-kosten', label: 'Kosten, Förderung, Strom & Tarife', kategorie: 'waermepumpe' },
  { value: 'repowering-entscheidung', label: 'Entscheidung & Kosten', kategorie: 'repowering' },
  { value: 'repowering-diagnose', label: 'Diagnose & Zustand', kategorie: 'repowering' },
  { value: 'repowering-umbau', label: 'Umbau, Erweiterung & Komponenten', kategorie: 'repowering' },
  { value: 'em-markt', label: 'Strommarkt & Tarife', kategorie: 'strom-energiemanagement' },
  { value: 'em-messung', label: 'Smart Meter & Messdaten', kategorie: 'strom-energiemanagement' },
  { value: 'em-netz', label: '§ 14a & Netzregeln', kategorie: 'strom-energiemanagement' },
  { value: 'em-hems', label: 'HEMS & Steuerung', kategorie: 'strom-energiemanagement' },
  { value: 'em-architektur', label: 'Lokal, Cloud & Schnittstellen', kategorie: 'strom-energiemanagement' },
  { value: 'em-eigenverbrauch', label: 'Speicher & Eigenverbrauch', kategorie: 'strom-energiemanagement' },
]

// Zuordnung Artikel → Cluster. Neue Artikel hier eintragen (oder im Artikel-Script `cluster` setzen).
export const CLUSTER_BY_SLUG = {
  // solaranlage
  'pv-anlage-planen': 'pv-planung',
  'wie-gross-sollte-eine-solaranlage-fuer-einfamilienhaus-sein': 'pv-planung',
  'ab-wieviel-qm-lohnt-sich-eine-solaranlage': 'pv-planung',
  'solarmodule-dach-voll-belegen-dachflaeche-freilassen': 'pv-planung',
  'ost-west-oder-sueddach-solaranlage': 'pv-planung',
  'pv-verschattung-leistungsoptimierer-stringdesign': 'pv-planung',
  'solaranlage-fuer-waermepumpe-auslegen': 'pv-planung',
  'solaranlage-fuer-e-auto-auslegen': 'pv-planung',
  'solaranlage-mit-oder-ohne-speicher': 'pv-planung',
  'typische-fehler-bei-solaranlagen': 'pv-planung',
  'braucht-man-einen-stromspeicher': 'pv-planung',
  'kosten-solaranlage-einfamilienhaus': 'pv-kosten',
  'kosten-solaranlage-mit-speicher-einfamilienhaus': 'pv-kosten',
  'kosten-10-kwp-solaranlage-mit-speicher': 'pv-kosten',
  'kosten-15-kwp-solaranlage-mit-speicher': 'pv-kosten',
  'amortisation-pv-anlage': 'pv-kosten',
  'wie-viel-strom-erzeugt-eine-10-kwp-solaranlage': 'pv-ertrag',
  'wie-viel-strom-erzeugt-eine-15-kwp-solaranlage': 'pv-ertrag',
  'was-bringt-eine-solaranlage-im-winter': 'pv-ertrag',
  'pv-anlage-liefert-weniger-als-berechnet-abweichung-normal': 'pv-ertrag',
  'hybrid-wechselrichter-oder-getrennte-geraete': 'pv-ertrag',
  'zaehlerschrank-pv-waermepumpe-smart-meter': 'pv-ertrag',
  'wie-viel-autarkie-ist-realistisch': 'pv-ertrag',
  'pv-anlage-bei-stromausfall-solarstrom-reicht-nicht': 'pv-ertrag',
  'photovoltaik-foerderung': 'pv-recht',
  'einspeiseverguetung-photovoltaik-2026': 'pv-recht',
  'eeg-2027-dach-pv-unter-25-kw': 'pv-recht',
  'photovoltaik-steuern': 'pv-recht',
  'pv-anlage-anmelden-marktstammdatenregister': 'pv-recht',
  'solardachpflicht-nrw-2026': 'pv-recht',
  'wer-darf-photovoltaikanlagen-installieren': 'pv-anbieter',
  'photovoltaik-testsieger': 'pv-anbieter',
  'garantie-vs-gewaehrleistung-pv-anlage': 'pv-anbieter',
  'solarmodule-40-jahre-garantie-produkt-leistung': 'pv-anbieter',
  'solarteur-insolvent-was-tun': 'pv-anbieter',
  'null-euro-anzahlung-photovoltaik': 'pv-anbieter',
  'solaranlage-gewerbedach': 'pv-gewerbe',
  'pv-gewerbe-wirtschaftlichkeit-beispielrechnung': 'pv-gewerbe',
  'pv-landwirtschaft-stalldach': 'pv-gewerbe',
  'mieterstrom-gemeinschaftliche-gebaeudeversorgung-2026': 'pv-gewerbe',
  // stromspeicher
  'lohnt-sich-ein-stromspeicher': 'speicher-nutzen',
  'wie-gross-sollte-ein-stromspeicher-sein': 'speicher-nutzen',
  'stromspeicher-kapazitaet-leistung-kw-kwh': 'speicher-nutzen',
  'stromspeicher-waermepumpe-nachts-versorgen': 'speicher-nutzen',
  'stromspeicher-im-winter-oft-leer': 'speicher-nutzen',
  'stromspeicher-kosten': 'speicher-kosten',
  'stromspeicher-foerderung-nrw': 'speicher-kosten',
  'cloud-speicher-stromspeicher-vergleich': 'speicher-kosten',
  'stromspeicher-nachruesten': 'speicher-kosten',
  'wie-lange-haelt-ein-stromspeicher': 'speicher-technik',
  'speicherwirkungsgrad-verluste-geladen-nutzbar': 'speicher-technik',
  'batteriezellen-stromspeicher-zellspannung-temperatur-balancing': 'speicher-technik',
  'stromspeicher-aufstellort-keller-garage-brandschutz': 'speicher-technik',
  'paragraf-14a-enwg-stromspeicher': 'speicher-technik',
  'notstrom-oder-ersatzstrom': 'speicher-technik',
  'lastspitzenkappung-stromspeicher-gewerbe': 'speicher-gewerbe',
  'gewerbespeicher-richtig-auslegen-lastgang-kw-kwh': 'speicher-gewerbe',
  'multi-use-stromspeicher': 'speicher-gewerbe',
  // wallbox
  'wallbox-zu-hause-laden': 'wallbox-planung',
  'wallbox-kosten': 'wallbox-planung',
  'wallbox-anmelden-netzbetreiber': 'wallbox-planung',
  'dienstwagen-zuhause-laden-wallbox-stromkosten-arbeitgeber': 'wallbox-planung',
  'wallbox-mit-pv-laden': 'wallbox-pv',
  'wallbox-phasenumschaltung-pv-ueberschussladen': 'wallbox-pv',
  'pv-ueberschussladen-funktioniert-nicht-ursachen': 'wallbox-pv',
  'bidirektionales-laden': 'wallbox-pv',
  'wallbox-11-oder-22-kw': 'wallbox-last',
  'lastmanagement-wallbox-hausanschluss-ueberlastung': 'wallbox-last',
  'zwei-e-autos-zuhause-laden-wallboxen-hausanschluss': 'wallbox-last',
  'paragraf-14a-enwg-steuerbare-verbrauchseinrichtungen': 'wallbox-last',
  // waermepumpe
  'wie-funktioniert-eine-waermepumpe': 'wp-grundlagen',
  'welche-waermepumpe-fuer-mein-haus': 'wp-grundlagen',
  'monoblock-oder-split-waermepumpe': 'wp-grundlagen',
  'jaz-wirkungsgrad': 'wp-grundlagen',
  'waermepumpe-im-altbau': 'wp-bestand',
  'waermepumpe-mit-heizkoerpern': 'wp-bestand',
  'waermepumpe-vorlauftemperatur': 'wp-bestand',
  'heizlastberechnung-waermepumpe': 'wp-bestand',
  'hydraulischer-abgleich-waermepumpe': 'wp-bestand',
  'pufferspeicher-waermepumpe': 'wp-bestand',
  'waermepumpe-richtig-aufstellen-standort-schall': 'wp-aufstellung',
  'waermepumpe-schallpegel': 'wp-aufstellung',
  'waermepumpe-abtauung-vereisung-kondensat': 'wp-aufstellung',
  'waermepumpe-richtig-einstellen': 'wp-betrieb',
  'waermepumpe-taktet-staendig-starts-normal': 'wp-betrieb',
  'heizstab-waermepumpe-sinnvoll-stromverbrauch': 'wp-betrieb',
  'warmwasser-waermepumpe-temperatur-legionellenschutz-kosten': 'wp-betrieb',
  'waermepumpe-lebensdauer-wartung': 'wp-betrieb',
  'waermepumpe-kosten-einfamilienhaus': 'wp-kosten',
  'waermepumpe-stromverbrauch-berechnen': 'wp-kosten',
  'waermepumpe-foerderung-2026': 'wp-kosten',
  'waermepumpentarif-oder-dynamischer-stromtarif': 'wp-kosten',
  '14a-enwg-waermepumpe-messkonzept-8': 'wp-kosten',
  'waermepumpe-und-photovoltaik': 'wp-kosten',
  // repowering
  'repowering-solaranlage': 'repowering-entscheidung',
  'alte-pv-anlage-nach-20-jahren': 'repowering-entscheidung',
  'repowering-vs-neuanlage': 'repowering-entscheidung',
  'repowering-kosten': 'repowering-entscheidung',
  'typische-fehler-beim-repowering': 'repowering-entscheidung',
  'wirtschaftlichkeit-eeg': 'repowering-entscheidung',
  'pv-anlage-fehlerdiagnose-stringmessung-isolation-hotspots': 'repowering-diagnose',
  'alte-pv-module-messen-leerlaufspannung-kurzschlussstrom-kennlinie': 'repowering-diagnose',
  'pid-hotspots-mikrorisse-delamination-pv-module': 'repowering-diagnose',
  'alten-wechselrichter-tauschen-moderne-wechselrichter-alte-pv-module': 'repowering-umbau',
  'alte-pv-anlage-erweitern-neue-anlage-daneben': 'repowering-umbau',
  'pv-anlage-dachsanierung-demontage-repowering': 'repowering-umbau',
  'speicher-nachruesten': 'repowering-umbau',
  'pv-anlage-rueckbau-montage': 'repowering-umbau',
  'notstrom-backup': 'repowering-umbau',
  'hems-monitoring-nachruesten': 'repowering-umbau',
  'pv-module-entsorgen-recycling': 'repowering-umbau',
  'komponenten-tausch-pv-anlage': 'repowering-umbau',
  // strom-energiemanagement
  'strommarkt-einfach-erklaert-boersenstrompreis-netzentgelt-strompreis': 'em-markt',
  'dynamischer-stromtarif-pv-speicher-lohnt-sich': 'em-markt',
  'negative-strompreise-2026-pv-speicher-eauto': 'em-markt',
  'dynamischer-stromtarif-paragraf-14a-netzentgelt': 'em-markt',
  'smart-meter-2026-pv-kosten-pflicht-vorteile': 'em-messung',
  'smart-meter-auslesen-verbrauchsdaten-trudi': 'em-messung',
  'westnetz-smart-meter-steuerbox-2026': 'em-messung',
  'lastgang-15-minuten-werte-verstehen': 'em-messung',
  'zeitvariable-netzentgelte-paragraph-14a-modul-3': 'em-netz',
  'steuerbox-paragraf-14a-smart-meter-hems': 'em-netz',
  'solarspitzengesetz-2026-60-prozent-negative-strompreise-smart-meter': 'em-netz',
  'hems-home-energy-management-system-hersteller-app': 'em-hems',
  'pv-speicher-wallbox-waermepumpe-intelligent-steuern': 'em-hems',
  'hems-wetterprognose-strompreis-ladezustand': 'em-hems',
  'pv-anlage-abregeln-strom-nutzen-hems-einspeisebegrenzung': 'em-hems',
  'cloud-ems-vs-lokales-ems-energiedaten': 'em-architektur',
  'internetausfall-pv-speicher-wallbox-hems': 'em-architektur',
  'lokales-hems-hersteller-cloud-server-internet-ausfall': 'em-architektur',
  'offene-schnittstellen-pv-speicher-hems-hersteller-app': 'em-architektur',
  'stromspeicher-aus-netz-laden-dynamisch-sinnvoll': 'em-eigenverbrauch',
  'eigenverbrauch-optimieren-100-prozent-autarkie': 'em-eigenverbrauch',
}

/** Cluster eines Artikels – explizit gesetzter Wert hat Vorrang vor der Zuordnung oben. */
export function resolveCluster(slug, explicitCluster) {
  return explicitCluster ?? CLUSTER_BY_SLUG[slug]
}

/** Prüft, ob ein Cluster zur Kategorie passt. */
export function isClusterOfKategorie(cluster, kategorie) {
  return RATGEBER_CLUSTERS.some((item) => item.value === cluster && item.kategorie === kategorie)
}
